apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1 
    config:
      node.master: true
      node.data: true
      node.ingest: true
    #podTemplate:                                                                                                                                
    #  metadata:                                                                                                                                 
    #    annotations:                                                                                                                            
    #      co.elastic.logs/enabled: "true"                                                                                                       
    #      co.elastic.logs/module: elasticsearch   
  #- nodeCount: 3
  #  config: 
  #    node.master: false
  #    node.data: true
  #    node.ingest: true
    #podTemplate:                                                                                                                                
    #  metadata:                                                                                                                                 
    #    annotations:                                                                                                                            
    #      co.elastic.logs/enabled: "true"                                                                                                       
    #      co.elastic.logs/module: elasticsearch   

