apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.3.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    # podTemplate:
    #  metadata:
    #    annotations:
    #      co.elastic.logs/enabled: "true"
    #      co.elastic.logs/module: elasticsearch
  #- nodeCount: 1
  #  config:
  #    node.master: true
  #    node.data: false
  #    node.ingest: false
  #  podTemplate:
  #    metadata:
  #        co.elastic.logs/enabled: "true"
  #        co.elastic.logs/module: elasticsearch
