
---
# All values need to be encode by the following command with the '-n' option
# echo -n 'STRING-TO-ENCODE' | base64
apiVersion: v1
kind: Secret
metadata:
  name: beats-demo
type: Opaque
data:
  # welcome1
  MYSQL_ROOT_PASSWORD: d2VsY29tZTE=
  MYSQL_PASSWORD: d2VsY29tZTE=
