apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      #annotations: 
      #  co.elastic.logs/enabled: "true"
      #  co.elastic.logs/module: mysql
      #  co.elastic.logs/fileset.stdout: slowlog
      #  co.elastic.logs/fileset.stderr: error   
      #  co.elastic.metrics/enabled: "true"     
      #  co.elastic.metrics/module: mysql
      #  co.elastic.metrics/metricsets: status 
      #  co.elastic.metrics/hosts: "root:${MYSQL_ROOT_PASSWORD}@tcp(127.0.0.1:3306)/"  
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: workshop-app
        - name: MYSQL_USER
          value: workshop
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workshop-app
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workshop-app
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
