apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      #annotations: 
      #  co.elastic.logs/enabled: "true"
      #  co.elastic.logs/module: nginx
      #  co.elastic.logs/fileset.stdout: access
      #  co.elastic.logs/fileset.stderr: error   
      #  co.elastic.metrics/enabled: "true"     
      #  co.elastic.metrics/module: nginx
      #  co.elastic.metrics/metricsets: stubstatus 
      #  co.elastic.metrics/hosts: "${data.host}:80"
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.6
        ports:
        - name: nginx-port 
          containerPort: 8081
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap  # Custom nginx configuration file, to enable stub_status, not enabled by default.
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
      include    /etc/nginx/mime.types;
      sendfile on;
      client_max_body_size 1M;
      root /usr/share/nginx/html/;
      index /index.html;

      server {
        listen 8081 default_server;

        location / {
           proxy_pass http://workshop-app-frontend:3000;
           proxy_set_header Host            $host;
           proxy_set_header X-Forwarded-For $remote_addr;
        }

      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nginx
