apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: workshop-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-app-frontend
  template:
    metadata:
      labels:
        app: workshop-app-frontend
      #annotations: 
      #  co.elastic.logs/enabled: "true" 
    spec:
      containers:
      - image: aclose/k8s-workshop-app-frontend:latest
        imagePullPolicy: Always
        name: app
        env:
        - name: BACKEND_SERVICE
          value: http://workshop-app-backend:1234
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: workshop-app-frontend
  labels:
    app: workshop-app-frontend
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: workshop-app-frontend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: workshop-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-app-backend
  template:
    metadata:
      labels:
        app: workshop-app-backend
      #annotations: 
      #  co.elastic.logs/enabled: "true" 
    spec:
      containers:
      - image: aclose/k8s-workshop-app-backend:latest
        imagePullPolicy: Always
        name: app
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workshop-app
              key: MYSQL_PASSWORD
        - name: DATABASE_URL
          value: mysql+pymysql://workshop:$(MYSQL_PASSWORD)@mysql:3306/workshop-app
        - name: PORT
          value: "1234"
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: workshop-app-backend
  labels:
    app: workshop-app-backend
spec:
  type: NodePort
  ports:
  - port: 1234
    targetPort: 1234
  selector:
    app: workshop-app-backend
